### ISSUE TITLE
Cannot open panel without any prior `textDocument/documentSymbol`query

### ISSUE THREAD

**Issue by przepompownia** [ldelossa/litee-symboltree.nvim#6] opened 2022-01-10 21:22 UTC
Reproduction: 

- see [#4 ](https://github.com/ldelossa/litee-symboltree.nvim/issues/4#issuecomment-1009314105) then run
`lua require('litee.lib.panel').toggle_panel()`

I get the message:
`Must open a litee component before toggling the panel`

But I would like to get working panel at the first call `toggle_panel()`. 

I can open the panel after running `lua vim.lsp.buf.document_symbol()`.

**Comment by ldelossa** [comment] 2022-01-10 21:27
That's correct. Theres no application state for a panel to be created.

**Comment by przepompownia** [comment] 2022-01-10 21:31
If I understood, it suggests to manually call for `textDocument/documentSymbol` before each opening the panel. Does it mean that the view isn't able to autorefresh after changing its source?

**Comment by ldelossa** [comment] 2022-01-10 21:34
You need to manually trigger at least one language server request for document symbol after that the panel will stay updated as you navigate around other files


This is handled by the refresh symbol tree auto command

**Comment by ldelossa** [comment] 2022-01-10 21:37
Going to close this, since this is by design, and is how the litee.nvim library works. However feel free to continue asking questions here, i will answer.

**Closed as completed by ldelossa** 2022-01-10 21:38 UTC

**Comment by przepompownia** [comment] 2022-01-10 22:22
The answer seems to be: 

- to use `on_open = 'panel'` config to open the panel with `textDocument/documentSymbol` 
- to use `lua require('litee.symboltree').popout_to()` to open this view in a float window.

**Comment by ldelossa** [comment] 2022-01-10 22:33
Ohhh, i did not realize you were trying to *not* use the popout UI. My bad. I thought you were saying you wanted to toggle open an *empty* panel.

**Comment by przepompownia** [comment] 2022-01-10 23:25
Currently I am interested only in litee-symboltree and no other part of litee. I am looking for some replacement for [symbols-outline](https://github.com/simrat39/symbols-outline.nvim) with less verbose UI. Thanks for providing an alternative. Hope such a use case can help provide more examples for beginners in the documentation.

**Comment by ldelossa** [comment] 2022-01-10 23:32
Yes, Thanks for bringing it up, I give the docs a second look soon.
